run:
  timeout: 5m

issues:
  # Dit is de "hou je mond" sectie
  exclude-rules:
    # Negeer "noctx" (http.NewRequest vs http.NewRequestWithContext in tests)
    - path: _test\.go
      linters: [noctx]

    # Negeer klachten over genegeerde errors voor specifieke functies
    - linters: [errcheck]
      text: "Error return value of `log.Sync` is not checked"

    # Negeer "stutter" (bv. user.UserStore) en "var-naming" (bv. AttachmentIDs)
    - linters: [revive]
      text: "stutters"
    - linters: [revive]
      text: "var-naming"

    # Negeer ongebruikte parameters (zoals 'ctx' of 'r' die je wel moet accepteren)
    - linters: [revive]
      text: "unused-parameter"

linters-settings:
  # Dit fixt de 'shadow' fout van net
  govet:
    enable:
      - shadow

linters:
  disable-all: true
  enable:
    # Dit zijn de moderne vervangers voor de oude linters
    - unused        # Vervangt structcheck, varcheck, deadcode
    - revive        # Vervangt golint
    - copyloopvar   # Vervangt exportloopref

    # Essentiële linters
    - errcheck
    - govet
    - staticcheck
    - goimports
    - gofmt

    # Goede "best practice" linters (die we nu temmen)
    - goconst
    - gocritic
    - gosec
    - noctx