run:
  timeout: 5m

# AANGEPAST: 'run.skip-dirs' is nu 'issues.exclude-dirs'
issues:
  exclude-dirs:
    - .github

linters-settings:
  # Instellingen om de linter minder vervelend te maken
  govet:
    enable:
      - shadow # Vervangt de oude 'check-shadowing'
  gocritic:
    # We negeren deze 'performance' fouten voor nu
    disabled-checks:
      - hugeParam
      - rangeValCopy
  gocyclo:
    min-complexity: 25 # Sta complexere functies toe (jouw max was 35)
  dupl:
    threshold: 150 # Sta meer duplicatie toe
  mnd:
    # Negeer 'magic numbers'
    checks: []
  revive:
    # Negeer klachten over 'stuttering' (bv. user.UserStore)
    ignore-generated-header: true
    rules:
      - name: var-naming
      - name: unused-parameter

linters:
  disable-all: true
  enable:
    # Dit zijn de moderne vervangers
    - unused        # Vervangt structcheck, varcheck, deadcode
    - revive        # Vervangt golint
    - mnd           # Vervangt gomnd
    - copyloopvar   # Vervangt exportloopref (sinds Go 1.22)

    # Essentiële linters
    - errcheck
    - govet
    - staticcheck
    - goimports
    - gofmt

    # Goede 'best practice' linters
    - goconst
    - gocyclo
    - gocritic
    - gosec
    - dupl
    - noctx