run:
  timeout: 5m
  skip-dirs:
    - .github

linters-settings:
  govet:
    enable:
      - shadow # Vervangt de oude 'check-shadowing'
  errcheck:
    # We negeren errors van .Close() en .Sync(), wat gebruikelijk is
    exclude-functions:
      - io.Closer.Close
      - go.uber.org/zap.Logger.Sync
  gocritic:
    enabled-tags:
      - performance
      - style
      - experimental
  gocyclo:
    min-complexity: 15 # Wees iets toleranter dan de default 10
  dupl:
    threshold: 100 # Default

linters:
  disable-all: true
  enable:
    # Dit zijn de moderne vervangers voor de linters waar hij over klaagde
    - unused      # Vervangt structcheck, varcheck, deadcode
    - revive      # Vervangt golint
    - mnd         # Vervangt gomnd
    - exportloopref # Vervangt scopelint

    # Essentiële linters
    - errcheck
    - govet
    - staticcheck
    - goimports
    - gofmt

    # Goede "best practice" linters
    - goconst
    - gocyclo
    - gocritic
    - gosec
    - dupl
    - noctx